/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminpageRouteImport } from './routes/adminpage'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CountryRouteImport } from './routes/country'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NigeriaPayRouteImport } from './routes/nigeria-pay'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PayRouteImport } from './routes/pay'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ApiDeskPassRouteImport } from './routes/api/desk-pass'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpageRoute = AdminpageRouteImport.update({
  id: '/adminpage',
  path: '/adminpage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryRoute = CountryRouteImport.update({
  id: '/country',
  path: '/country',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NigeriaPayRoute = NigeriaPayRouteImport.update({
  id: '/nigeria-pay',
  path: '/nigeria-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskPassRoute = ApiDeskPassRouteImport.update({
  id: '/api/desk-pass',
  path: '/api/desk-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adminpage': typeof AdminpageRoute
  '/connect': typeof ConnectRoute
  '/country': typeof CountryRoute
  '/login': typeof LoginRoute
  '/nigeria-pay': typeof NigeriaPayRoute
  '/packages': typeof PackagesRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/session': typeof SessionRoute
  '/api/desk-pass': typeof ApiDeskPassRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adminpage': typeof AdminpageRoute
  '/connect': typeof ConnectRoute
  '/country': typeof CountryRoute
  '/login': typeof LoginRoute
  '/nigeria-pay': typeof NigeriaPayRoute
  '/packages': typeof PackagesRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/session': typeof SessionRoute
  '/api/desk-pass': typeof ApiDeskPassRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adminpage': typeof AdminpageRoute
  '/connect': typeof ConnectRoute
  '/country': typeof CountryRoute
  '/login': typeof LoginRoute
  '/nigeria-pay': typeof NigeriaPayRoute
  '/packages': typeof PackagesRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/pay': typeof PayRoute
  '/register': typeof RegisterRoute
  '/session': typeof SessionRoute
  '/api/desk-pass': typeof ApiDeskPassRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adminpage'
    | '/connect'
    | '/country'
    | '/login'
    | '/nigeria-pay'
    | '/packages'
    | '/partner'
    | '/partners'
    | '/pay'
    | '/register'
    | '/session'
    | '/api/desk-pass'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/adminpage'
    | '/connect'
    | '/country'
    | '/login'
    | '/nigeria-pay'
    | '/packages'
    | '/partner'
    | '/partners'
    | '/pay'
    | '/register'
    | '/session'
    | '/api/desk-pass'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adminpage'
    | '/connect'
    | '/country'
    | '/login'
    | '/nigeria-pay'
    | '/packages'
    | '/partner'
    | '/partners'
    | '/pay'
    | '/register'
    | '/session'
    | '/api/desk-pass'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminpageRoute: typeof AdminpageRoute
  ConnectRoute: typeof ConnectRoute
  CountryRoute: typeof CountryRoute
  LoginRoute: typeof LoginRoute
  NigeriaPayRoute: typeof NigeriaPayRoute
  PackagesRoute: typeof PackagesRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PayRoute: typeof PayRoute
  RegisterRoute: typeof RegisterRoute
  SessionRoute: typeof SessionRoute
  ApiDeskPassRoute: typeof ApiDeskPassRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpage': {
      id: '/adminpage'
      path: '/adminpage'
      fullPath: '/adminpage'
      preLoaderRoute: typeof AdminpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country': {
      id: '/country'
      path: '/country'
      fullPath: '/country'
      preLoaderRoute: typeof CountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nigeria-pay': {
      id: '/nigeria-pay'
      path: '/nigeria-pay'
      fullPath: '/nigeria-pay'
      preLoaderRoute: typeof NigeriaPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-pass': {
      id: '/api/desk-pass'
      path: '/api/desk-pass'
      fullPath: '/api/desk-pass'
      preLoaderRoute: typeof ApiDeskPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminpageRoute: AdminpageRoute,
  ConnectRoute: ConnectRoute,
  CountryRoute: CountryRoute,
  LoginRoute: LoginRoute,
  NigeriaPayRoute: NigeriaPayRoute,
  PackagesRoute: PackagesRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PayRoute: PayRoute,
  RegisterRoute: RegisterRoute,
  SessionRoute: SessionRoute,
  ApiDeskPassRoute: ApiDeskPassRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
